export{default as Home} from './Home/Home';
export{default as Fwd} from './Fwd/Fwd';
export{default as Everyday} from './Everyday/Everyday';
export{default as Luxe} from './Luxe/Luxe';
export{default as Profiel} from './Profile/Profiel';
export {default as Search} from './Search/Search';
export {default as Notifications} from './Notification/Notifications';
export {default as Weshlist} from './WeshList/Weshlist';
export {default as Baseket} from './Basetket/Baseket';
export {default as Ordertocontinue} from './Ordetocontinue/Ordertocontinue';
export {default as Detailitemscreen} from './Detailitemscreen/Detailitemscreen';
export {default as Addproducts} from './Addproducts/Addproducts';
export {default as Loginscreen} from './Loginscreen/Loginscreen';